export const AppStyles = {
  color: {
    black: '#000000',
    darkGray: '#999999',
    gray: '#707070',
    border: '#E7E7E7',
    white: '#FFFFFF',
    pink: '#FF4EA5',
    hotPink: '#FF3196',
    lightGray: '#EDEDED',
    placeholder: '#707070',
    backgroundGray: '#F9F9F9',
    subTitle: '#777777',
    IconColor: '#808080',
    SelectImage: '#FAFAFA',
    SelectImageBorder: '#DEDEDE',
    midGray: '#8E8E8E',
    midBlack: '#0C0C0C',
    nonActiveIcon: '#A2A2A2',
  },
  padding: {
    screen: 32.06,
    small: 26.45,
    large: 52.06,
  },
  IconSize: {
    small: 15,
    middle: 18,
    large: 21,
    xlarge: 24,
  },
  font: {
    small: 12,
    subTitle: 14,
    middle: 15,
    large: 20,
    title: 23,
    xlarge: 24,
  },
  fontStyle: {
    thin: 'NotoSansKR-Thin',
    light: 'NotoSansKR-Light',
    regular: 'NotoSansKR-Regular',
    medium: 'NotoSansKR-Medium',
    bold: 'NotoSansKR-Bold',
    black: 'NotoSansKR-Black',
  },
  fontFamily: {
    bold: 'AppleSDGothicNeo-Bold',
    medium: 'AppleSDGothicNeoM',
    light: 'AppleSDGothicNeoL',
  },
};
